version: '3'
services:
  mariadb:
    build:
      context: ./requirements/MariaDB
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - mynetwork

  nginx:
    build:
      context: ./requirements/NGINX
      dockerfile: Dockerfile
    ports:
      - 443:443
    networks:
      - mynetwork
  wordpress:
    build:
      context: ./requirements/WordPress
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - mynetwork
networks:
  mynetwork:

volumes:
  mariadb_data:
  wordpress_data: 
