version: '3'

volumes:
  mariadb:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/eelmoham/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/eelmoham/data/wordpress
services:
  mariadb:
    build:
      context: ./requirements/MariaDB
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql
  nginx:
    build:
      context: ./requirements/NGINX
      dockerfile: Dockerfile
    ports:
      - 443:443
    depends_on:
      - wordpress
    volumes:
      - wordpress:/usr/share/nginx/html

  wordpress:
    build:
      context: ./requirements/WordPress
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    depends_on:
      - mariadb
    volumes:
      - wordpress:/usr/share/nginx/html
